In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
dataset = pd.read_csv('http://iali.in/datasets/Social_Network_Ads.csv')

In [3]:
dataset.head(10)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [0]:
dataset['Gender'] = dataset['Gender'].astype('category').cat.codes

In [0]:
features = ['Gender','Age', 'EstimatedSalary']

In [0]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(dataset, test_size=0.2)

In [0]:
X_train, X_test = train[features], test[features]
y_train, y_test = train['Purchased'], test['Purchased']

In [0]:
from sklearn.ensemble import RandomForestClassifier

rfcmodel = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=3, random_state=1)
rfcmodel.fit(X_train,y_train)

predictions = rfcmodel.predict(X_test)

In [0]:
import pickle

pickle.dump(rfcmodel, open('model.pkl','wb'))